format.version=1
codec.revision=native-codecs.3
cef.source.commit=82195616d8405e6081a0d90924707b82aa9e4141
chromium.version=146.0.7680.179
media.use-ffmpeg=true
ffmpeg.branding=Chromium
proprietary.codecs=true
windows.h264.decoder=D3D11
windows.aac.decoder=MediaFoundation
macos.h264.decoder=VideoToolbox
macos.aac.decoder=AudioToolbox
